In [2]:
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier as RFC
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix

In [3]:
ds=pd.read_csv(r"C:\Users\arunf\OneDrive\Documents\Data Science\Machine Learning\DataSet\diabetes (3) (2).csv")

In [4]:
ds

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [5]:
ds.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [6]:
train,test=train_test_split(ds,test_size=0.2)

In [7]:
trainx=train.iloc[:,:8]
trainy=train.iloc[:,8]
testx=test.iloc[:,:8]
testy=test.iloc[:,8]

In [8]:
trainx

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
125,1,88,30,42,99,55.0,0.496,26
233,4,122,68,0,0,35.0,0.394,29
632,2,111,60,0,0,26.2,0.343,23
102,0,125,96,0,0,22.5,0.262,21
678,3,121,52,0,0,36.0,0.127,25
...,...,...,...,...,...,...,...,...
451,2,134,70,0,0,28.9,0.542,23
439,6,107,88,0,0,36.8,0.727,31
19,1,115,70,30,96,34.6,0.529,32
76,7,62,78,0,0,32.6,0.391,41
298,14,100,78,25,184,36.6,0.412,46

In [9]:
trainy

125    1
233    0
632    0
102    0
678    1
      ..
451    1
439    0
19     1
76     0
298    1
Name: Outcome, Length: 614, dtype: int64

In [10]:
rfc=RFC(n_jobs=8,n_estimators=20,oob_score=True,criterion='entropy')

In [12]:
pred=rfc.fit(trainx,trainy).predict(testx)
cm=confusion_matrix(pred,testy)
acc=np.mean(pred==testy.values.flatten())

In [13]:
cm

array([[83, 18],
       [16, 37]], dtype=int64)

In [14]:
mean=(83+37)/(83+37+18+16)
mean

0.7792207792207793

In [15]:
acc

0.7792207792207793